In [322]:
import pandas as pd
import numpy as np

In [323]:
# Read the dataset using Pandas 
dataframe = pd.read_csv("http://archive.ics.uci.edu/ml/machine-learning-databases/car/car.data", 
                 names = ["buying", "maint", "doors", "persons", "lug_boot", "safety", "Class" ])        

In [324]:
# Replacing categorical labels with integer values
dataframe = dataframe.replace('vhigh',4)
dataframe = dataframe.replace('high',3)
dataframe = dataframe.replace('med',2)
dataframe = dataframe.replace('low',1)
dataframe = dataframe.replace('5more',6)
dataframe = dataframe.replace('more',5)
dataframe = dataframe.replace('small',1)
dataframe = dataframe.replace('med',2)
dataframe = dataframe.replace('big',3)
dataframe = dataframe.replace('unacc',1)
dataframe = dataframe.replace('acc',2)
dataframe = dataframe.replace('good',3)
dataframe = dataframe.replace('vgood',4)

car = dataframe.values

In [325]:
dataframe.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1728 entries, 0 to 1727
Data columns (total 7 columns):
buying      1728 non-null int64
maint       1728 non-null int64
doors       1728 non-null object
persons     1728 non-null object
lug_boot    1728 non-null int64
safety      1728 non-null int64
Class       1728 non-null int64
dtypes: int64(5), object(2)
memory usage: 94.6+ KB


In [326]:
X,y = car[:,:6], car[:,6]

In [327]:
X,y = X.astype(float), y.astype(float)

In [328]:
# Splitting the data into training and testing
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.2,random_state=0)

# Scaling the data
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [329]:
scaler.fit(X_train)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [330]:
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [331]:
# Create the model and tune the the parameters
from sklearn.neural_network import MLPClassifier
mlp = MLPClassifier(solver='lbfgs', alpha=1e-5, hidden_layer_sizes=(4, 5),
                   activation='tanh', max_iter=2000)
mlp.fit(X_train,y_train)

MLPClassifier(activation='tanh', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(4, 5), learning_rate='constant',
       learning_rate_init=0.001, max_iter=2000, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=None,
       shuffle=True, solver='lbfgs', tol=0.0001, validation_fraction=0.1,
       verbose=False, warm_start=False)

In [332]:
predictions = mlp.predict(X_test)

In [333]:
# Performance Evaluation From Confusion Matrix and Classification Report
from sklearn.metrics import classification_report,confusion_matrix
print("\n\nConfusion Matrix  \n\n", confusion_matrix(y_test,predictions))
print("\nClassification Report  \n\n", classification_report(y_test,predictions))



Confusion Matrix  

 [[240   0   0   0]
 [  2  76   0   1]
 [  0   0  17   0]
 [  0   0   0  10]]

Classification Report  

              precision    recall  f1-score   support

        1.0       0.99      1.00      1.00       240
        2.0       1.00      0.96      0.98        79
        3.0       1.00      1.00      1.00        17
        4.0       0.91      1.00      0.95        10

avg / total       0.99      0.99      0.99       346



In [334]:
mlp.loss_

0.029027895579691619

In [335]:
mlp.score(X_test, y_test)

0.99132947976878616